module.exports = {
    "rules": {
      "indentation": 2,
      "block-no-empty": null,
      "block-opening-brace-newline-after": "always-multi-line",
      "block-opening-brace-space-after": "always-single-line",
      "block-opening-brace-space-before": "always",
      "color-hex-case": "lower",
      "color-hex-length": "short",
      "color-no-invalid-hex": true,
      "comment-empty-line-before": "always",
      "declaration-block-no-shorthand-property-overrides": true,
      "declaration-block-semicolon-newline-after": "always-multi-line",
      "declaration-block-semicolon-space-after": "always-single-line",
      "declaration-block-semicolon-space-before": "never",
      "declaration-block-single-line-max-declarations": 1,
      "declaration-block-trailing-semicolon": "always",
      "declaration-colon-newline-after": "always-multi-line",
      "declaration-colon-space-after": "always-single-line",
      "declaration-colon-space-before": "never",
      "declaration-bang-space-after": "never",
      "declaration-bang-space-before": "always",
      "function-calc-no-unspaced-operator": true,
      "function-comma-newline-after": "always-multi-line",
      "function-comma-space-after": "always-single-line",
      "function-comma-space-before": "never",
      "function-linear-gradient-no-nonstandard-direction": true,
      "function-parentheses-newline-inside": "always-multi-line",
      "function-parentheses-space-inside": "never-single-line",
      "function-whitespace-after": "always",
      "max-nesting-depth": 2,
      "media-feature-colon-space-after": "always",
      "media-feature-colon-space-before": "never",
      "media-feature-name-no-vendor-prefix": true,
      "media-feature-range-operator-space-after": "always",
      "media-feature-range-operator-space-before": "always",
      "media-query-list-comma-newline-after": "always-multi-line",
      "media-query-list-comma-space-after": "always-single-line",
      "media-query-list-comma-space-before": "never",
      "no-eol-whitespace": true,
      "number-leading-zero": "always",
      "selector-no-qualifying-type": [true, { "ignore": "attribute" }],
      // SUIT CSS naming conventions
      // SUIT was chosen for its terse naming syntax vs BEM
      // See here for naming conventions: https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md
      "selector-class-pattern": /^(?:u|is|has)\-[a-z][a-zA-Z0-9]*$|^(?!u|is|has)[a-zA-Z][a-zA-Z0-9]*(?:\-[a-z][a-zA-Z0-9]*)?(?:\-\-[a-z][a-zA-Z0-9]*)?$/,
      "value-list-comma-newline-after": "always-multi-line",
      "value-list-comma-space-after": "always-single-line",
      "value-list-comma-space-before": "never",
      "value-no-vendor-prefix": true,
    }
  }
